# -*- encoding: utf-8 -*-

=begin
#Placetel API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0-SNAPSHOT

=end

$:.push File.expand_path("../lib", __FILE__)
require "placetel_api/version"

Gem::Specification.new do |s|
  s.name        = "placetel_api"
  s.version     = PlacetelAPI::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OpenAPI-Generator"]
  s.email       = [""]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "Placetel API Ruby Gem"
  s.description = "No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 3.3"

  s.add_runtime_dependency 'typhoeus', '~> 1.0'
  s.add_runtime_dependency 'json', '~> 2.10'

  s.add_development_dependency 'rspec', '~> 3.6'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
