=begin
#Placetel API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for PlacetelApi::CallDetailRecordsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CallDetailRecordsApi' do
  before do
    # run before each test
    @api_instance = PlacetelApi::CallDetailRecordsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CallDetailRecordsApi' do
    it 'should create an instance of CallDetailRecordsApi' do
      expect(@api_instance).to be_instance_of(PlacetelApi::CallDetailRecordsApi)
    end
  end

  # unit tests for get_call_detail_records
  # Get call detail records
  # Provides a list of call detail records
  # @param date YYYY-MM-DD
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page of results to fetch.
  # @option opts [Integer] :per_page Number of results to return per page.
  # @return [Array<CallDetailRecord>]
  describe 'get_call_detail_records test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
