=begin
#Placetel API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for PlacetelApi::CallCenterApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CallCenterApi' do
  before do
    # run before each test
    @api_instance = PlacetelApi::CallCenterApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CallCenterApi' do
    it 'should create an instance of CallCenterApi' do
      expect(@api_instance).to be_instance_of(PlacetelApi::CallCenterApi)
    end
  end

  # unit tests for get_call_center_agents
  # Fetch all call center agents
  # Provides a list of all call center agents
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page of results to fetch.
  # @option opts [Integer] :per_page Number of results to return per page.
  # @return [Array<CallCenterAgent>]
  describe 'get_call_center_agents test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_call_center_calls
  # Fetch all call center calls
  # Provides a list of all call center calls
  # @param date YYYY-MM-DD
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page of results to fetch.
  # @option opts [Integer] :per_page Number of results to return per page.
  # @return [Array<CallCenterCall>]
  describe 'get_call_center_calls test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_call_center_agents_id
  # Update a agent
  # Update a agent by its ID
  # @param id Sip user ID
  # @param call_center_agents 
  # @param [Hash] opts the optional parameters
  # @return [CallCenterAgent]
  describe 'put_call_center_agents_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
