=begin
#Placetel API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for PlacetelApi::ContactsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ContactsApi' do
  before do
    # run before each test
    @api_instance = PlacetelApi::ContactsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContactsApi' do
    it 'should create an instance of ContactsApi' do
      expect(@api_instance).to be_instance_of(PlacetelApi::ContactsApi)
    end
  end

  # unit tests for delete_contacts_id
  # Deletes a contact
  # Deletes a contact by its ID
  # @param id Contact ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_contacts_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_contacts
  # Get all contacts
  # Provides a list of all contacts
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :filter_speeddial 
  # @option opts [String] :filter_first_name 
  # @option opts [String] :filter_last_name 
  # @option opts [String] :filter_company 
  # @option opts [String] :filter_email 
  # @option opts [String] :filter_email_work 
  # @option opts [String] :filter_phone_work 
  # @option opts [String] :filter_mobile_work 
  # @option opts [String] :filter_phone 
  # @option opts [String] :filter_mobile 
  # @option opts [Object] :filter_blocked 
  # @option opts [String] :search_number 
  # @option opts [Integer] :page Page of results to fetch.
  # @option opts [Integer] :per_page Number of results to return per page.
  # @return [Array<Contact>]
  describe 'get_contacts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_contacts_id
  # Retrieve a contact
  # Fetches a contact by its ID
  # @param id ID of a contact
  # @param [Hash] opts the optional parameters
  # @return [Contact]
  describe 'get_contacts_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_contacts
  # Create a contact
  # Creates a contact
  # @param contacts 
  # @param [Hash] opts the optional parameters
  # @return [Contact]
  describe 'post_contacts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_contacts_id
  # Update a contact
  # Updates a contact for a given ID
  # @param id Contact ID
  # @param contacts 
  # @param [Hash] opts the optional parameters
  # @return [Contact]
  describe 'put_contacts_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
