=begin
#Placetel API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for PlacetelAPI::FaxesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FaxesApi' do
  before do
    # run before each test
    @api_instance = PlacetelAPI::FaxesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FaxesApi' do
    it 'should create an instance of FaxesApi' do
      expect(@api_instance).to be_instance_of(PlacetelAPI::FaxesApi)
    end
  end

  # unit tests for delete_faxes_id
  # Delete a fax
  # Delete a fax by its ID
  # @param id Fax ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_faxes_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_faxes
  # Fetch in- and outbound faxes
  # Provides a list of all faxes
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter_type 
  # @option opts [String] :filter_from_number 
  # @option opts [String] :filter_to_number 
  # @option opts [String] :order 
  # @option opts [Integer] :page Page of results to fetch.
  # @option opts [Integer] :per_page Number of results to return per page.
  # @return [Array<Fax>]
  describe 'get_faxes test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_faxes_id
  # Fetch specific fax
  # Fetch in- or outbound fax
  # @param id Fax ID
  # @param [Hash] opts the optional parameters
  # @return [Fax]
  describe 'get_faxes_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_faxes
  # Create outbound fax
  # Sends faxes via API call
  # @param faxes 
  # @param [Hash] opts the optional parameters
  # @return [Fax]
  describe 'post_faxes test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
