=begin
#Placetel API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for PlacetelAPI::GroupsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GroupsApi' do
  before do
    # run before each test
    @api_instance = PlacetelAPI::GroupsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GroupsApi' do
    it 'should create an instance of GroupsApi' do
      expect(@api_instance).to be_instance_of(PlacetelAPI::GroupsApi)
    end
  end

  # unit tests for delete_groups_id
  # Delete a group
  # Delete a group by its ID
  # @param id Group ID
  # @param [Hash] opts the optional parameters
  # @return [Group]
  describe 'delete_groups_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_groups
  # Fetch all groups
  # Fetch a list of all groups
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter_name 
  # @option opts [String] :filter_description 
  # @option opts [String] :filter_type 
  # @option opts [Integer] :page Page of results to fetch.
  # @option opts [Integer] :per_page Number of results to return per page.
  # @return [Array<Group>]
  describe 'get_groups test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_groups_id
  # Fetch a group
  # Fetch a groups by its ID
  # @param id Group ID
  # @param [Hash] opts the optional parameters
  # @return [Group]
  describe 'get_groups_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_groups
  # Create a group
  # Create a new group
  # @param groups 
  # @param [Hash] opts the optional parameters
  # @return [Group]
  describe 'post_groups test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_groups_id
  # Update a group
  # Update a group by its ID
  # @param id Group ID
  # @param groups 
  # @param [Hash] opts the optional parameters
  # @return [Group]
  describe 'put_groups_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
