=begin
#Placetel API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for PlacetelAPI::NumbersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'NumbersApi' do
  before do
    # run before each test
    @api_instance = PlacetelAPI::NumbersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NumbersApi' do
    it 'should create an instance of NumbersApi' do
      expect(@api_instance).to be_instance_of(PlacetelAPI::NumbersApi)
    end
  end

  # unit tests for delete_numbers_number_id_profiles_id
  # Delete a profile for a number
  # Removes the profile for a number
  # @param number_id Number ID
  # @param id Profile ID
  # @param [Hash] opts the optional parameters
  # @return [Profile]
  describe 'delete_numbers_number_id_profiles_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_numbers
  # Get all numbers
  # Provides a list of all numbers
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter_prefix 
  # @option opts [String] :filter_number 
  # @option opts [Object] :filter_activated 
  # @option opts [String] :filter_name 
  # @option opts [String] :filter_description 
  # @option opts [Integer] :page Page of results to fetch.
  # @option opts [Integer] :per_page Number of results to return per page.
  # @return [Array<Number>]
  describe 'get_numbers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_numbers_id
  # Retrieve a number
  # Fetches a number by its ID
  # @param id Number ID
  # @param [Hash] opts the optional parameters
  # @return [Number]
  describe 'get_numbers_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_numbers_number_id_profiles
  # List profiles for a number
  # Lists all available profiles for a number 
  # @param number_id Number ID
  # @param [Hash] opts the optional parameters
  # @return [Profile]
  describe 'get_numbers_number_id_profiles test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_numbers_number_id_profiles
  # Creates a new profile for a number
  # Shows the active profile for a number
  # @param number_id Number ID
  # @param unknown_base_type 
  # @param [Hash] opts the optional parameters
  # @return [Profile]
  describe 'post_numbers_number_id_profiles test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_numbers_number_id_profiles
  # Activates a profile for a number
  # Change the active profile for a number
  # @param number_id Number ID
  # @param unknown_base_type 
  # @param [Hash] opts the optional parameters
  # @return [Profile]
  describe 'put_numbers_number_id_profiles test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
