=begin
#Placetel API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for PlacetelApi::PromptsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PromptsApi' do
  before do
    # run before each test
    @api_instance = PlacetelApi::PromptsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PromptsApi' do
    it 'should create an instance of PromptsApi' do
      expect(@api_instance).to be_instance_of(PlacetelApi::PromptsApi)
    end
  end

  # unit tests for delete_prompts_id
  # Delete a prompt
  # Delete a prompt by its ID
  # @param id Prompt ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_prompts_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_prompts
  # Fetch all prompts
  # Provides a list of all prompts
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter_name 
  # @option opts [String] :filter_description 
  # @option opts [Integer] :page Page of results to fetch.
  # @option opts [Integer] :per_page Number of results to return per page.
  # @return [Array<Prompt>]
  describe 'get_prompts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_prompts_id
  # Retrieve a prompt
  # Fetches a prompt by its ID
  # @param id Prompt ID
  # @param [Hash] opts the optional parameters
  # @return [Prompt]
  describe 'get_prompts_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_prompts
  # Create a prompt
  # Creates a new prompt
  # @param prompts 
  # @param [Hash] opts the optional parameters
  # @return [Prompt]
  describe 'post_prompts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_prompts_id
  # Update a prompt
  # Update a prompt by its ID
  # @param id Prompt ID
  # @param prompts 
  # @param [Hash] opts the optional parameters
  # @return [Prompt]
  describe 'put_prompts_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
