=begin
#Placetel API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for PlacetelAPI::ProvisioningsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProvisioningsApi' do
  before do
    # run before each test
    @api_instance = PlacetelAPI::ProvisioningsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProvisioningsApi' do
    it 'should create an instance of ProvisioningsApi' do
      expect(@api_instance).to be_instance_of(PlacetelAPI::ProvisioningsApi)
    end
  end

  # unit tests for delete_provisionings_id
  # Delete a phone provisionings
  # Delete a phone provisioning
  # @param id ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_provisionings_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_provisionings
  # Get all phone provisionings
  # Provides a full list of all registered provisioned phones
  # @param [Hash] opts the optional parameters
  # @option opts [String] :search 
  # @option opts [Integer] :page Page of results to fetch.
  # @option opts [Integer] :per_page Number of results to return per page.
  # @return [Array<Provisioning>]
  describe 'get_provisionings test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_provisionings_id
  # Retrieve a phone provisionings
  # Fetches a phone provisioning by its ID
  # @param id ID
  # @param [Hash] opts the optional parameters
  # @return [Provisioning]
  describe 'get_provisionings_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_provisionings
  # Creates a phone provisionings
  # Creates a phone provisioning
  # @param provisionings 
  # @param [Hash] opts the optional parameters
  # @return [Provisioning]
  describe 'post_provisionings test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_provisionings_id_reconfigure
  # Trigger reconfiguration of a phone
  # This sends a SIP command to the user on line 1 to fetch configuration changes.
  # @param id ID
  # @param [Hash] opts the optional parameters
  # @return [Provisioning]
  describe 'post_provisionings_id_reconfigure test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_provisionings_id
  # Update a phone provisionings
  # Updates a phone provisioning
  # @param id ID
  # @param provisionings 
  # @param [Hash] opts the optional parameters
  # @return [Provisioning]
  describe 'put_provisionings_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
