=begin
#Placetel API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for PlacetelAPI::SipUsersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SipUsersApi' do
  before do
    # run before each test
    @api_instance = PlacetelAPI::SipUsersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SipUsersApi' do
    it 'should create an instance of SipUsersApi' do
      expect(@api_instance).to be_instance_of(PlacetelAPI::SipUsersApi)
    end
  end

  # unit tests for delete_sip_users_id
  # Delete a sip user
  # Delete a sip user by its ID
  # @param id Sip user ID
  # @param [Hash] opts the optional parameters
  # @return [SipUser]
  describe 'delete_sip_users_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_sip_users_id_short_codes_code_id
  # Delete short code
  # Delete sip user short code
  # @param id Sip user ID
  # @param code_id Short code ID
  # @param [Hash] opts the optional parameters
  # @return [ShortCode]
  describe 'delete_sip_users_id_short_codes_code_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_sip_users
  # Fetch all sip users
  # Fetch a list of all sip users
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :filter_did 
  # @option opts [String] :filter_username 
  # @option opts [String] :filter_name 
  # @option opts [String] :filter_description 
  # @option opts [Integer] :page Page of results to fetch.
  # @option opts [Integer] :per_page Number of results to return per page.
  # @return [Array<SipUser>]
  describe 'get_sip_users test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_sip_users_id
  # Fetch a sip user
  # Fetch a sip users by its ID
  # @param id Sip user ID
  # @param [Hash] opts the optional parameters
  # @return [SipUser]
  describe 'get_sip_users_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_sip_users_id_short_codes
  # Short codes
  # List sip user short codes
  # @param id Sip user ID
  # @param [Hash] opts the optional parameters
  # @return [ShortCode]
  describe 'get_sip_users_id_short_codes test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_sip_users
  # Create a sip user
  # Create a new sip user
  # @param sip_users 
  # @param [Hash] opts the optional parameters
  # @return [SipUser]
  describe 'post_sip_users test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_sip_users_id_short_codes
  # Create short code
  # Create sip user short code
  # @param id Sip user ID
  # @param sip_users_id_short_codes 
  # @param [Hash] opts the optional parameters
  # @return [ShortCode]
  describe 'post_sip_users_id_short_codes test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_sip_users_id
  # Update a sip user
  # Update a sip user by its ID
  # @param id Sip user ID
  # @param sip_users 
  # @param [Hash] opts the optional parameters
  # @return [SipUser]
  describe 'put_sip_users_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
