=begin
#Placetel API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0-SNAPSHOT

=end

require 'date'

module PlacetelAPI
  # Create a sip user
  class PostSipUsers
    attr_accessor :name

    attr_accessor :type

    attr_accessor :description

    attr_accessor :did

    attr_accessor :callerid

    attr_accessor :webuser_id

    attr_accessor :automatic_prefix

    attr_accessor :blocked_prefixes

    attr_accessor :routing_plan_id

    attr_accessor :hotdesk_login

    attr_accessor :hotdesk_pin

    attr_accessor :hotdesk_type

    attr_accessor :hotdesk_provisioning_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'type' => :'type',
        :'description' => :'description',
        :'did' => :'did',
        :'callerid' => :'callerid',
        :'webuser_id' => :'webuser_id',
        :'automatic_prefix' => :'automatic_prefix',
        :'blocked_prefixes' => :'blocked_prefixes',
        :'routing_plan_id' => :'routing_plan_id',
        :'hotdesk_login' => :'hotdesk_login',
        :'hotdesk_pin' => :'hotdesk_pin',
        :'hotdesk_type' => :'hotdesk_type',
        :'hotdesk_provisioning_id' => :'hotdesk_provisioning_id'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'type' => :'String',
        :'description' => :'String',
        :'did' => :'Integer',
        :'callerid' => :'String',
        :'webuser_id' => :'Integer',
        :'automatic_prefix' => :'String',
        :'blocked_prefixes' => :'String',
        :'routing_plan_id' => :'Integer',
        :'hotdesk_login' => :'String',
        :'hotdesk_pin' => :'String',
        :'hotdesk_type' => :'String',
        :'hotdesk_provisioning_id' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlacetelAPI::PostSipUsers` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlacetelAPI::PostSipUsers`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'did')
        self.did = attributes[:'did']
      end

      if attributes.key?(:'callerid')
        self.callerid = attributes[:'callerid']
      end

      if attributes.key?(:'webuser_id')
        self.webuser_id = attributes[:'webuser_id']
      end

      if attributes.key?(:'automatic_prefix')
        self.automatic_prefix = attributes[:'automatic_prefix']
      end

      if attributes.key?(:'blocked_prefixes')
        self.blocked_prefixes = attributes[:'blocked_prefixes']
      end

      if attributes.key?(:'routing_plan_id')
        self.routing_plan_id = attributes[:'routing_plan_id']
      end

      if attributes.key?(:'hotdesk_login')
        self.hotdesk_login = attributes[:'hotdesk_login']
      end

      if attributes.key?(:'hotdesk_pin')
        self.hotdesk_pin = attributes[:'hotdesk_pin']
      end

      if attributes.key?(:'hotdesk_type')
        self.hotdesk_type = attributes[:'hotdesk_type']
      end

      if attributes.key?(:'hotdesk_provisioning_id')
        self.hotdesk_provisioning_id = attributes[:'hotdesk_provisioning_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @name.nil?
      return false if @type.nil?
      type_validator = EnumAttributeValidator.new('String', ["legacy_standard", "blf", "standard", "fax", "trunk"])
      return false unless type_validator.valid?(@type)
      hotdesk_type_validator = EnumAttributeValidator.new('String', ["standard", "custom", "global_did"])
      return false unless hotdesk_type_validator.valid?(@hotdesk_type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ["legacy_standard", "blf", "standard", "fax", "trunk"])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] hotdesk_type Object to be assigned
    def hotdesk_type=(hotdesk_type)
      validator = EnumAttributeValidator.new('String', ["standard", "custom", "global_did"])
      unless validator.valid?(hotdesk_type)
        fail ArgumentError, "invalid value for \"hotdesk_type\", must be one of #{validator.allowable_values}."
      end
      @hotdesk_type = hotdesk_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          type == o.type &&
          description == o.description &&
          did == o.did &&
          callerid == o.callerid &&
          webuser_id == o.webuser_id &&
          automatic_prefix == o.automatic_prefix &&
          blocked_prefixes == o.blocked_prefixes &&
          routing_plan_id == o.routing_plan_id &&
          hotdesk_login == o.hotdesk_login &&
          hotdesk_pin == o.hotdesk_pin &&
          hotdesk_type == o.hotdesk_type &&
          hotdesk_provisioning_id == o.hotdesk_provisioning_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, type, description, did, callerid, webuser_id, automatic_prefix, blocked_prefixes, routing_plan_id, hotdesk_login, hotdesk_pin, hotdesk_type, hotdesk_provisioning_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        PlacetelAPI.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end
        
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
