=begin
#Placetel API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0-SNAPSHOT

=end

require 'date'

module PlacetelAPI
  class PutRoutingsIvr
    attr_accessor :prompt_id

    attr_accessor :item_1_id

    attr_accessor :item_2_id

    attr_accessor :item_3_id

    attr_accessor :item_4_id

    attr_accessor :item_5_id

    attr_accessor :item_6_id

    attr_accessor :item_7_id

    attr_accessor :item_8_id

    attr_accessor :item_9_id

    attr_accessor :catchall_routing_object_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'prompt_id' => :'prompt_id',
        :'item_1_id' => :'item_1_id',
        :'item_2_id' => :'item_2_id',
        :'item_3_id' => :'item_3_id',
        :'item_4_id' => :'item_4_id',
        :'item_5_id' => :'item_5_id',
        :'item_6_id' => :'item_6_id',
        :'item_7_id' => :'item_7_id',
        :'item_8_id' => :'item_8_id',
        :'item_9_id' => :'item_9_id',
        :'catchall_routing_object_id' => :'catchall_routing_object_id'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'prompt_id' => :'Integer',
        :'item_1_id' => :'Integer',
        :'item_2_id' => :'Integer',
        :'item_3_id' => :'Integer',
        :'item_4_id' => :'Integer',
        :'item_5_id' => :'Integer',
        :'item_6_id' => :'Integer',
        :'item_7_id' => :'Integer',
        :'item_8_id' => :'Integer',
        :'item_9_id' => :'Integer',
        :'catchall_routing_object_id' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlacetelAPI::PutRoutingsIvr` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlacetelAPI::PutRoutingsIvr`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'prompt_id')
        self.prompt_id = attributes[:'prompt_id']
      end

      if attributes.key?(:'item_1_id')
        self.item_1_id = attributes[:'item_1_id']
      end

      if attributes.key?(:'item_2_id')
        self.item_2_id = attributes[:'item_2_id']
      end

      if attributes.key?(:'item_3_id')
        self.item_3_id = attributes[:'item_3_id']
      end

      if attributes.key?(:'item_4_id')
        self.item_4_id = attributes[:'item_4_id']
      end

      if attributes.key?(:'item_5_id')
        self.item_5_id = attributes[:'item_5_id']
      end

      if attributes.key?(:'item_6_id')
        self.item_6_id = attributes[:'item_6_id']
      end

      if attributes.key?(:'item_7_id')
        self.item_7_id = attributes[:'item_7_id']
      end

      if attributes.key?(:'item_8_id')
        self.item_8_id = attributes[:'item_8_id']
      end

      if attributes.key?(:'item_9_id')
        self.item_9_id = attributes[:'item_9_id']
      end

      if attributes.key?(:'catchall_routing_object_id')
        self.catchall_routing_object_id = attributes[:'catchall_routing_object_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          prompt_id == o.prompt_id &&
          item_1_id == o.item_1_id &&
          item_2_id == o.item_2_id &&
          item_3_id == o.item_3_id &&
          item_4_id == o.item_4_id &&
          item_5_id == o.item_5_id &&
          item_6_id == o.item_6_id &&
          item_7_id == o.item_7_id &&
          item_8_id == o.item_8_id &&
          item_9_id == o.item_9_id &&
          catchall_routing_object_id == o.catchall_routing_object_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [prompt_id, item_1_id, item_2_id, item_3_id, item_4_id, item_5_id, item_6_id, item_7_id, item_8_id, item_9_id, catchall_routing_object_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        PlacetelAPI.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end
        
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
