=begin
#Placetel API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PlacetelAPI::PostCtiMacStartTransfer
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PostCtiMacStartTransfer' do
  before do
    # run before each test
    @instance = PlacetelAPI::PostCtiMacStartTransfer.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PostCtiMacStartTransfer' do
    it 'should create an instance of PostCtiMacStartTransfer' do
      expect(@instance).to be_instance_of(PlacetelAPI::PostCtiMacStartTransfer)
    end
  end
  describe 'test attribute "line"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "call_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
