=begin
#Placetel API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0-SNAPSHOT

=end

# Common files
require 'placetel_api/api_client'
require 'placetel_api/api_error'
require 'placetel_api/version'
require 'placetel_api/configuration'

# Models
require 'placetel_api/models/call'
require 'placetel_api/models/call_center_agent'
require 'placetel_api/models/call_center_call'
require 'placetel_api/models/call_center_queue'
require 'placetel_api/models/call_detail_record'
require 'placetel_api/models/call_to_number'
require 'placetel_api/models/contact'
require 'placetel_api/models/custom_configuration'
require 'placetel_api/models/device'
require 'placetel_api/models/fax'
require 'placetel_api/models/group'
require 'placetel_api/models/key'
require 'placetel_api/models/line'
require 'placetel_api/models/me'
require 'placetel_api/models/number'
require 'placetel_api/models/post_calls'
require 'placetel_api/models/post_contacts'
require 'placetel_api/models/post_cti_mac_answer'
require 'placetel_api/models/post_cti_mac_blind_transfer'
require 'placetel_api/models/post_cti_mac_complete_conference'
require 'placetel_api/models/post_cti_mac_complete_transfer'
require 'placetel_api/models/post_cti_mac_decline'
require 'placetel_api/models/post_cti_mac_dial'
require 'placetel_api/models/post_cti_mac_dial_digit'
require 'placetel_api/models/post_cti_mac_hangup'
require 'placetel_api/models/post_cti_mac_hold'
require 'placetel_api/models/post_cti_mac_resume'
require 'placetel_api/models/post_cti_mac_send_dtmf_digits'
require 'placetel_api/models/post_cti_mac_start_conference'
require 'placetel_api/models/post_cti_mac_start_transfer'
require 'placetel_api/models/post_faxes'
require 'placetel_api/models/post_groups'
require 'placetel_api/models/post_prompts'
require 'placetel_api/models/post_provisionings'
require 'placetel_api/models/post_routing_plans'
require 'placetel_api/models/post_routings'
require 'placetel_api/models/post_sip_users'
require 'placetel_api/models/post_sip_users_id_short_codes'
require 'placetel_api/models/post_sms'
require 'placetel_api/models/post_users'
require 'placetel_api/models/profile'
require 'placetel_api/models/prompt'
require 'placetel_api/models/provisioning'
require 'placetel_api/models/put_call_center_agents'
require 'placetel_api/models/put_contacts'
require 'placetel_api/models/put_cti'
require 'placetel_api/models/put_groups'
require 'placetel_api/models/put_prompts'
require 'placetel_api/models/put_provisionings'
require 'placetel_api/models/put_provisionings_id_custom_configurations'
require 'placetel_api/models/put_provisionings_id_custom_configurations_configurations'
require 'placetel_api/models/put_provisionings_keys'
require 'placetel_api/models/put_routing_plans'
require 'placetel_api/models/put_routings'
require 'placetel_api/models/put_routings_api'
require 'placetel_api/models/put_routings_custom_callerid'
require 'placetel_api/models/put_routings_forward'
require 'placetel_api/models/put_routings_forward_destinations'
require 'placetel_api/models/put_routings_group'
require 'placetel_api/models/put_routings_ivr'
require 'placetel_api/models/put_routings_mailbox'
require 'placetel_api/models/put_routings_notification'
require 'placetel_api/models/put_routings_plan'
require 'placetel_api/models/put_routings_queue'
require 'placetel_api/models/put_routings_time_settings'
require 'placetel_api/models/put_sip_users'
require 'placetel_api/models/put_subscriptions'
require 'placetel_api/models/put_users'
require 'placetel_api/models/recording'
require 'placetel_api/models/routing_object'
require 'placetel_api/models/routing_object_api'
require 'placetel_api/models/routing_object_custom_caller_id'
require 'placetel_api/models/routing_object_forward'
require 'placetel_api/models/routing_object_group'
require 'placetel_api/models/routing_object_ivr'
require 'placetel_api/models/routing_object_mailbox'
require 'placetel_api/models/routing_object_notification'
require 'placetel_api/models/routing_object_plan'
require 'placetel_api/models/routing_object_time_settings'
require 'placetel_api/models/routing_plan'
require 'placetel_api/models/short_code'
require 'placetel_api/models/sip_user'
require 'placetel_api/models/subscription'
require 'placetel_api/models/user'

# APIs
require 'placetel_api/api/cti_api'
require 'placetel_api/api/call_center_api'
require 'placetel_api/api/call_detail_records_api'
require 'placetel_api/api/calls_api'
require 'placetel_api/api/contacts_api'
require 'placetel_api/api/devices_api'
require 'placetel_api/api/faxes_api'
require 'placetel_api/api/groups_api'
require 'placetel_api/api/numbers_api'
require 'placetel_api/api/prompts_api'
require 'placetel_api/api/provisionings_api'
require 'placetel_api/api/recordings_api'
require 'placetel_api/api/routing_plans_api'
require 'placetel_api/api/routings_api'
require 'placetel_api/api/sms_api'
require 'placetel_api/api/sip_users_api'
require 'placetel_api/api/subscriptions_api'
require 'placetel_api/api/users_api'

module PlacetelAPI
  class << self
    # Customize default settings for the SDK using block.
    #   PlacetelAPI.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
